#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipinfo.io/ip);
DOMAIN=`cat /etc/xray/domain`
ADDR="s/xxxxxxxxx/$DOMAIN/g";

function ovpn_install() {
    rm -rf /etc/openvpn
    mkdir -p /etc/openvpn
    wget -O /etc/openvpn/vpn.zip "https://raw.githubusercontent.com/NevermoreSSH/VVV/main/openvpn/vpn.zip" >/dev/null 2>&1 
    unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip
    rm -f /etc/openvpn/vpn.zip
    chown -R root:root /etc/openvpn/server/easy-rsa/
}
function config_easy() {
    cd
    mkdir -p /usr/lib/openvpn/
    cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
    sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
    systemctl enable --now openvpn-server@server-tcp
    systemctl enable --now openvpn-server@server-udp
    /etc/init.d/openvpn restart
}

function make_follow() {
    echo 1 > /proc/sys/net/ipv4/ip_forward
    sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
    
cat > /etc/openvpn/"$DOMAIN"-tcp.ovpn <<-END
client
dev tun
proto tcp
remote $DOMAIN 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
remote-cert-tls server
key-direction 1
END
    
cat > /etc/openvpn/"$DOMAIN"-udp.ovpn <<-END
client
dev tun
proto udp
remote $DOMAIN 2200
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
remote-cert-tls server
key-direction 1
END
    
cat > /etc/openvpn/"$DOMAIN"-ws-ssl.ovpn <<-END
client
dev tun
proto tcp
remote $DOMAIN 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
remote-cert-tls server
key-direction 1
END

cat > /etc/openvpn/"$DOMAIN"-ssl.ovpn <<-END
client
dev tun
proto tcp
remote $DOMAIN 443
resolv-retry infinite
route-method exe
nobind
persist-key
persist-tun
auth-user-pass
comp-lzo
verb 3
remote-cert-tls server
key-direction 1
END
}

function cert_ovpn() {
    # Ensure certificates exist
    if [ ! -f /etc/openvpn/server/ca.crt ]; then
        echo "Error: CA certificate not found!"
        return 1
    fi
    
    for config in "$DOMAIN"-tcp "$DOMAIN"-udp "$DOMAIN"-ws-ssl "$DOMAIN"-ssl; do
        if [ -f /etc/openvpn/"$config".ovpn ]; then
            echo '<ca>' >> /etc/openvpn/"$config".ovpn
            cat /etc/openvpn/server/ca.crt >> /etc/openvpn/"$config".ovpn
            echo '</ca>' >> /etc/openvpn/"$config".ovpn
        fi
    done
    
    # Copy to web directory
    cp /etc/openvpn/"$DOMAIN"-tcp.ovpn /var/www/html/"$DOMAIN"-tcp.ovpn
    cp /etc/openvpn/"$DOMAIN"-udp.ovpn /var/www/html/"$DOMAIN"-udp.ovpn
    cp /etc/openvpn/"$DOMAIN"-ws-ssl.ovpn /var/www/html/"$DOMAIN"-ws-ssl.ovpn
    cp /etc/openvpn/"$DOMAIN"-ws-ssl.ovpn /var/www/html/"$DOMAIN"-ssl.ovpn
}

function install_ovpn() {
    ovpn_install
    config_easy
    make_follow
    cert_ovpn
    systemctl enable --now openvpn
    
    # Restart services to ensure proper loading
    systemctl restart openvpn-server@server-tcp
    systemctl restart openvpn-server@server-udp
    
    echo "OpenVPN installation completed!"
    echo "Client configs available at:"
    echo "/etc/openvpn/$DOMAIN-tcp.ovpn"
    echo "/etc/openvpn/$DOMAIN-udp.ovpn"
    echo "/var/www/html/$DOMAIN-tcp.ovpn"
    echo "/var/www/html/$DOMAIN-udp.ovpn"
}

install_ovpn
